/**
 * `aacsearch completion` — shell completion setup for bash, zsh, fish
 */

import { writeFileSync, existsSync } from "fs";
import { createInterface } from "readline/promises";

import { Command } from "commander";

import { getConfigDir } from "../lib/config.js";

export const completionCommand = new Command("completion")
	.description("Generate shell completion scripts")
	.argument("[shell]", "Shell type: bash, zsh, fish (default: auto-detect)")
	.option("--install", "Install completions to the default location")
	.option("--print", "Print completion script to stdout")
	.action(async (shellArg: string | undefined, options: { install?: boolean; print?: boolean }) => {
		const shell = shellArg ?? detectShell();
		const validShells = ["bash", "zsh", "fish"];

		if (!validShells.includes(shell)) {
			console.error(`Error: Unsupported shell "${shell}". Supported: ${validShells.join(", ")}`);
			process.exit(1);
		}

		const script = generateCompletionScript(shell);

		if (options.print) {
			console.log(script);
			return;
		}

		if (options.install) {
			await installCompletion(shell, script);
			return;
		}

		// Interactive mode
		console.log(`AACsearch shell completions for ${shell}`);
		console.log("");
		console.log(script);
		console.log("");

		const rl = createInterface({
			input: process.stdin,
			output: process.stdout,
		});
		const answer = await rl.question("Install to default location? [y/N]: ");
		rl.close();

		if (answer.toLowerCase() === "y" || answer.toLowerCase() === "yes") {
			await installCompletion(shell, script);
		} else {
			console.log(
				`To use, add the output to your ${shell} config (e.g. source <(aacsearch completion ${shell})).`,
			);
		}
	});

function detectShell(): string {
	const shellEnv = process.env.SHELL ?? "";
	if (shellEnv.includes("zsh")) return "zsh";
	if (shellEnv.includes("fish")) return "fish";
	return "bash";
}

async function installCompletion(shell: string, script: string): Promise<void> {
	const { homedir } = await import("os");
	const { join } = await import("path");
	const home = homedir();

	let installPath: string;
	let sourceCmd: string;

	switch (shell) {
		case "bash":
			installPath = join(getConfigDir(), "completions", "aacsearch.bash");
			sourceCmd = `source ${installPath}`;
			break;
		case "zsh": {
			const zshDir = join(home, ".zsh-completions");
			installPath = join(zshDir, "_aacsearch");
			sourceCmd = `fpath+=(${zshDir})`;
			break;
		}
		case "fish":
			installPath = join(home, ".config", "fish", "completions", "aacsearch.fish");
			sourceCmd =
				"# Completions installed — fish loads them automatically from ~/.config/fish/completions/";
			break;
		default:
			throw new Error(`Unsupported shell: ${shell}`);
	}

	const { mkdirSync } = await import("fs");
	const { dirname } = await import("path");
	mkdirSync(dirname(installPath), { recursive: true });
	writeFileSync(installPath, script, "utf-8");

	console.log(`✓ Completions installed to ${installPath}`);
	console.log("");
	console.log(`To activate, add this to your ${shell} config:`);
	console.log(`  ${sourceCmd}`);
}

function generateCompletionScript(shell: string): string {
	switch (shell) {
		case "bash":
			return generateBashCompletions();
		case "zsh":
			return generateZshCompletions();
		case "fish":
			return generateFishCompletions();
		default:
			return "";
	}
}

function generateBashCompletions(): string {
	const D = "$";
	return `# AACsearch CLI bash completion
# Generated by \`aacsearch completion bash\`
# Add to ~/.bashrc: source <(aacsearch completion bash)

_aacsearch()
{
    local cur prev words cword
    _init_completion || return

    local commands="completion init login collections documents search keys reindex monitor migrate"
    local global_opts="--help --version --json"

    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "${D}commands ${D}global_opts" -- "${D}cur"))
        return
    fi

    case "${D}{words[1]}" in
        collections)
            local subcommands="list create delete"
            local opts="--json --help"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${D}subcommands ${D}opts" -- "${D}cur"))
            fi
            ;;
        documents)
            local subcommands="import export list"
            local opts="--collection -c --json --help"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${D}subcommands ${D}opts" -- "${D}cur"))
            fi
            ;;
        keys)
            local subcommands="list create revoke rotate"
            local opts="--json --help"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${D}subcommands ${D}opts" -- "${D}cur"))
            fi
            ;;
        search)
            local opts="--collection -c --query-by --filter-by --facet-by --sort-by --per-page --page --json --help"
            COMPREPLY=($(compgen -W "${D}opts" -- "${D}cur"))
            ;;
        reindex)
            local opts="--collection -c --force -f --json --help"
            COMPREPLY=($(compgen -W "${D}opts" -- "${D}cur"))
            ;;
        monitor)
            local opts="--interval -i --collection -c --help"
            COMPREPLY=($(compgen -W "${D}opts" -- "${D}cur"))
            ;;
        migrate)
            local opts="--from -f --collection -c --dry-run --json --help"
            COMPREPLY=($(compgen -W "${D}opts" -- "${D}cur"))
            ;;
        completion)
            local shells="bash zsh fish"
            local opts="--install --print --help"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${D}shells ${D}opts" -- "${D}cur"))
            fi
            ;;
        login|init)
            local opts="--help"
            COMPREPLY=($(compgen -W "${D}opts" -- "${D}cur"))
            ;;
    esac
} &&
    complete -F _aacsearch aacsearch
`;
}

function generateZshCompletions(): string {
	return `#compdef aacsearch
# AACsearch CLI zsh completion
# Generated by \`aacsearch completion zsh\`

_aacsearch_commands() {
    local -a commands
    commands=(
        'completion:Generate shell completion scripts'
        'init:Scaffold a config file'
        'login:Authenticate with AACsearch'
        'collections:Manage search collections (indexes)'
        'documents:Import and export documents'
        'search:Search across a collection'
        'keys:Manage API keys'
        'reindex:Trigger reindex on a collection'
        'monitor:Live search metrics dashboard'
        'migrate:Migrate search data from other providers'
    )
    _describe 'command' commands
}

_aacsearch() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \\
        '--help[Show help]' \\
        '--version[Show version]' \\
        '--json[Output as JSON]' \\
        '1: :_aacsearch_commands' \\
        '*::arg:->args'

    case $words[1] in
        collections)
            _arguments -C \\
                '--json[Output as JSON]' \\
                '1: :(list create delete)' \\
                '*::arg:->args'
            ;;
        documents)
            _arguments -C \\
                '--collection[A collection slug]:slug:' \\
                '--json[Output as JSON]' \\
                '1: :(import export list)' \\
                '*::arg:->args'
            ;;
        keys)
            _arguments -C \\
                '--json[Output as JSON]' \\
                '1: :(list create revoke rotate)' \\
                '*::arg:->args'
            ;;
        search)
            _arguments \\
                '--collection[A collection slug]:slug:' \\
                '--query-by[Fields to search]:fields:' \\
                '--filter-by[Filter expression]:filter:' \\
                '--facet-by[Facet fields]:facets:' \\
                '--sort-by[Sort field and direction]:sort:' \\
                '--per-page[Results per page]:n:' \\
                '--page[Page number]:n:' \\
                '--json[Output as JSON]' \\
                '--help[Show help]'
            ;;
        reindex)
            _arguments \\
                '--collection[A collection slug]:slug:' \\
                '--force[Skip confirmation]' \\
                '--json[Output as JSON]'
            ;;
        monitor)
            _arguments \\
                '--interval[Refresh interval]:seconds:' \\
                '--collection[Filter to collection]:slug:'
            ;;
        migrate)
            _arguments \\
                '--from[Source provider]:provider:(algolia elasticsearch solr)' \\
                '--collection[Target collection slug]:slug:' \\
                '--dry-run[Preview without importing]' \\
                '--json[Output as JSON]'
            ;;
        completion)
            _arguments \\
                '--install[Install to default location]' \\
                '--print[Print to stdout]' \\
                '1: :(bash zsh fish)'
            ;;
    esac
}

_aacsearch
`;
}

function generateFishCompletions(): string {
	return `# AACsearch CLI fish completion
# Generated by \`aacsearch completion fish\`
# Install: ~/.config/fish/completions/aacsearch.fish

# Commands
complete -c aacsearch -f -n "__fish_use_subcommand" -a completion -d "Generate shell completion scripts"
complete -c aacsearch -f -n "__fish_use_subcommand" -a init -d "Scaffold a config file"
complete -c aacsearch -f -n "__fish_use_subcommand" -a login -d "Authenticate with AACsearch"
complete -c aacsearch -f -n "__fish_use_subcommand" -a collections -d "Manage search collections (indexes)"
complete -c aacsearch -f -n "__fish_use_subcommand" -a documents -d "Import and export documents"
complete -c aacsearch -f -n "__fish_use_subcommand" -a search -d "Search across a collection"
complete -c aacsearch -f -n "__fish_use_subcommand" -a keys -d "Manage API keys"
complete -c aacsearch -f -n "__fish_use_subcommand" -a reindex -d "Trigger reindex on a collection"
complete -c aacsearch -f -n "__fish_use_subcommand" -a monitor -d "Live search metrics dashboard"
complete -c aacsearch -f -n "__fish_use_subcommand" -a migrate -d "Migrate search data from other providers"

# Global options
complete -c aacsearch -n "__fish_use_subcommand" -l json -d "Output as JSON"
complete -c aacsearch -n "__fish_use_subcommand" -l help -d "Show help"
complete -c aacsearch -n "__fish_use_subcommand" -l version -d "Show version"

# collections subcommands
complete -c aacsearch -n "__fish_seen_subcommand_from collections" -a list -d "List all collections"
complete -c aacsearch -n "__fish_seen_subcommand_from collections" -a create -d "Create a new collection"
complete -c aacsearch -n "__fish_seen_subcommand_from collections" -a delete -d "Delete a collection"

# documents subcommands
complete -c aacsearch -n "__fish_seen_subcommand_from documents" -a import -d "Import documents from file or stdin"
complete -c aacsearch -n "__fish_seen_subcommand_from documents" -a export -d "Export documents from a collection"
complete -c aacsearch -n "__fish_seen_subcommand_from documents" -a list -d "List documents in a collection"
complete -c aacsearch -n "__fish_seen_subcommand_from documents" -l collection -s c -r -d "Collection slug"

# keys subcommands
complete -c aacsearch -n "__fish_seen_subcommand_from keys" -a list -d "List all API keys"
complete -c aacsearch -n "__fish_seen_subcommand_from keys" -a create -d "Create a new API key"
complete -c aacsearch -n "__fish_seen_subcommand_from keys" -a revoke -d "Revoke an API key"
complete -c aacsearch -n "__fish_seen_subcommand_from keys" -a rotate -d "Rotate an API key"

# search options
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l collection -s c -r -d "Collection slug"
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l query-by -r -d "Fields to search"
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l filter-by -r -d "Filter expression"
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l facet-by -r -d "Facet fields"
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l sort-by -r -d "Sort field and direction"
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l per-page -r -d "Results per page"
complete -c aacsearch -n "__fish_seen_subcommand_from search" -l page -r -d "Page number"

# reindex options
complete -c aacsearch -n "__fish_seen_subcommand_from reindex" -l collection -s c -r -d "Collection slug"
complete -c aacsearch -n "__fish_seen_subcommand_from reindex" -l force -s f -d "Skip confirmation"

# monitor options
complete -c aacsearch -n "__fish_seen_subcommand_from monitor" -l interval -s i -r -d "Refresh interval (seconds)"
complete -c aacsearch -n "__fish_seen_subcommand_from monitor" -l collection -s c -r -d "Filter to collection"

# migrate options
complete -c aacsearch -n "__fish_seen_subcommand_from migrate" -l from -s f -x -a "algolia elasticsearch solr" -d "Source provider"
complete -c aacsearch -n "__fish_seen_subcommand_from migrate" -l collection -s c -r -d "Target collection"
complete -c aacsearch -n "__fish_seen_subcommand_from migrate" -l dry-run -d "Preview without importing"

# completion options
complete -c aacsearch -n "__fish_seen_subcommand_from completion" -l install -d "Install to default location"
complete -c aacsearch -n "__fish_seen_subcommand_from completion" -l print -d "Print to stdout"
complete -c aacsearch -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
`;
}
