/**
 * `aacsearch init` — scaffold a .aacsearch.yaml config file
 */

import { writeFileSync, existsSync } from "fs";
import { join, resolve } from "path";
import { createInterface } from "readline/promises";

import { Command } from "commander";

import { loadConfig } from "../lib/config.js";

export const initCommand = new Command("init")
	.description("Scaffold an AACsearch config file in the current directory")
	.option("-f, --force", "Overwrite existing config")
	.action(async (options: { force?: boolean }) => {
		const configPath = join(resolve("."), ".aacsearch.yaml");

		if (existsSync(configPath) && !options.force) {
			console.error(".aacsearch.yaml already exists. Use --force to overwrite.");
			process.exit(1);
		}

		const rl = createInterface({ input: process.stdin, output: process.stdout });
		const existing = loadConfig();

		const endpoint =
			((await rl.question(`API endpoint (${existing.endpoint ?? "https://api.aacsearch.io"}): `)) ||
				existing.endpoint) ??
			"https://api.aacsearch.io";
		const projectId =
			((await rl.question(`Project ID (${existing.projectId ?? "(optional)"}): `)) ||
				existing.projectId) ??
			"";
		const apiKey =
			((await rl.question(
				`API key (${existing.apiKey ? "(already configured)" : "required"}): `,
			)) ||
				existing.apiKey) ??
			"";
		rl.close();

		const yaml = `# AACsearch configuration
# Generated by \`aacsearch init\`

endpoint: ${endpoint}
${projectId ? `projectId: ${projectId}` : ""}
${apiKey ? `apiKey: ${apiKey}` : ""}
`;

		writeFileSync(configPath, yaml, "utf-8");
		console.log(`✓ Created ${configPath}`);
	});
