-- Add new document source types to the KnowledgeSourceType enum
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_DOCX';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_XLSX';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_PPTX';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_EPUB';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_IMG';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_AUDIO';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_VIDEO';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_CSV';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_JSON';
ALTER TYPE "KnowledgeSourceType" ADD VALUE IF NOT EXISTS 'FILE_TXT';
